---
# SPDX-FileCopyrightText: 2023 - 2025 Ali Sajid Imami
#
# SPDX-License-Identifier: Apache-2.0
# SPDX-License-Identifier: MIT
name: "Feature request"
description: "Suggest an idea for this project"
title: "[FEATURE]"
labels: ["enhancement"]
assignees: ["AliSajid"]
body:
    - type: markdown
      attributes:
        value: "## Is your feature request related to a problem?\nDescribe the problem clearly. Ex: 'I'm always frustrated when...'"
    - type: textarea
      id: problem_description
      attributes:
        label: "Problem Description"
        description: "Explain the problem that led to this feature request."
      validations:
        required: true
    - type: markdown
      attributes:
        value: "## Describe the solution you'd like\nA clear and concise description of what you want to happen."
    - type: textarea
      id: solution_description
      attributes:
        label: "Proposed Solution"
        description: "Describe the feature or change you'd like to see."
      validations:
        required: true
    - type: markdown
      attributes:
        value: "## Describe alternatives you've considered\nA clear and concise description of any alternative solutions or features you've considered."
    - type: textarea
      id: alternative_solutions
      attributes:
        label: "Alternative Solutions"
        description: "List any alternative approaches you've thought about."
    - type: markdown
      attributes:
        value: "## Additional context\nAdd any other context or screenshots about the feature request here."
    - type: textarea
      id: additional_context
      attributes:
        label: "Additional Context"
        description: "Provide any extra details, including screenshots if applicable."
