# SPDX-FileCopyrightText: 2024 - 2025 Ali Sajid Imami
#
# SPDX-License-Identifier: Apache-2.0
# SPDX-License-Identifier: MIT

[package]
name = "gh-bofh-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies.gh-bofh]
path = ".."

[dependencies]
libfuzzer-sys = "0.4"

[[bin]]
name = "fuzz_random_classic"
path = "fuzz_targets/fuzz_random_classic.rs"
test = false
doc = false

[[bin]]
name = "fuzz_random_modern"
path = "fuzz_targets/fuzz_random_modern.rs"
test = false
doc = false

[profile.release]
debug = 1
