---
# SPDX-FileCopyrightText: 2023 - 2025 Ali Sajid Imami
#
# SPDX-License-Identifier: Apache-2.0
# SPDX-License-Identifier: MIT
name: Code Coverage
on:
    workflow_call:
jobs:
    test:
        name: Generate Coverage
        runs-on: ubuntu-latest
        container:
            image: xd009642/tarpaulin:develop-nightly@sha256:5d51ef547294f1c8ead44805936dbe358df709be060072c508234ea62684d486
            options: --security-opt seccomp=unconfined

        steps:
            - name: Harden Runner
              uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
              with:
                egress-policy: audit
            - name: Checkout repository
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

            - uses: dtolnay/rust-toolchain@56f84321dbccf38fb67ce29ab63e4754056677e0 # nightly
              with:
                toolchain: nightly
                components: llvm-tools-preview

            - name: Install necessary tools
              uses: taiki-e/install-action@9903ab6feadaec33945de535fe9d181b91802a55 # v2.50.0
              with:
                tool: cargo-llvm-cov,nextest,cargo-tarpaulin

            - name: Collect coverage data (including doctests)
              run: cargo +nightly tarpaulin --verbose --all-features --workspace --timeout 120 --out xml

            - name: Upload to codecov.io
              uses: codecov/codecov-action@ad3126e916f78f00edff4ed0317cf185271ccc2d # v5.4.2
              with:
                token: ${{ secrets.CODECOV_TOKEN }}
                verbose: true
                working-directory: .
            - name: Upload coverage reports to Codacy
              uses: codacy/codacy-coverage-reporter-action@89d6c85cfafaec52c72b6c5e8b2878d33104c699 # 1.3.0
              with:
                project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
                coverage-reports: cobertura.xml
                language: Rust
