---
# SPDX-FileCopyrightText: 2023 - 2025 Ali Sajid Imami
#
# SPDX-License-Identifier: Apache-2.0
# SPDX-License-Identifier: MIT
name: Code Coverage
on:
    workflow_call:
jobs:
    test:
        name: Generate Coverage
        runs-on: ubuntu-latest
        container:
            image: xd009642/tarpaulin:develop-nightly@sha256:8ce264482050f0ed81f7dd29710a5f592e70b1a371a545610b172348503030f5
            options: --security-opt seccomp=unconfined

        steps:
            - name: Harden Runner
              uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
              with:
                egress-policy: audit
            - name: Checkout repository
              uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

            - uses: dtolnay/rust-toolchain@b3b07ba8b418998c39fb20f53e8b695cdcc8de1b # nightly
              with:
                toolchain: nightly
                components: llvm-tools-preview

            - name: Install necessary tools
              uses: taiki-e/install-action@5c27e59d8c472d2a91731d8b5d7fe040fad53387 # v2.58.18
              with:
                tool: cargo-llvm-cov,nextest,cargo-tarpaulin

            - name: Collect coverage data (including doctests)
              run: cargo +nightly tarpaulin --verbose --all-features --workspace --timeout 120 --out xml

            - name: Upload to codecov.io
              uses: codecov/codecov-action@fdcc8476540edceab3de004e990f80d881c6cc00 # v5.5.0
              with:
                token: ${{ secrets.CODECOV_TOKEN }}
                verbose: true
                working-directory: .
            - name: Upload coverage reports to Codacy
              uses: codacy/codacy-coverage-reporter-action@89d6c85cfafaec52c72b6c5e8b2878d33104c699 # 1.3.0
              with:
                project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
                coverage-reports: cobertura.xml
                language: Rust
