---
# SPDX-FileCopyrightText: 2023 - 2025 Ali Sajid Imami
#
# SPDX-License-Identifier: Apache-2.0
# SPDX-License-Identifier: MIT
name: Code Coverage
on:
    workflow_call:
jobs:
    test:
        name: Generate Coverage
        runs-on: ubuntu-latest
        container:
            image: xd009642/tarpaulin:develop-nightly@sha256:6af080dd06a60f69091123b079c3a2d3b5e4f806d7aa039661bffe48b2380c9f
            options: --security-opt seccomp=unconfined

        steps:
            - name: Harden Runner
              uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
              with:
                egress-policy: audit
            - name: Checkout repository
              uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

            - uses: dtolnay/rust-toolchain@e97e2d8cc328f1b50210efc529dca0028893a2d9 # nightly
              with:
                toolchain: nightly
                components: llvm-tools-preview

            - name: Install necessary tools
              uses: taiki-e/install-action@133a13585eb96b576726757d256e9531cd6dddf2 # v2.58.32
              with:
                tool: cargo-llvm-cov,nextest,cargo-tarpaulin

            - name: Collect coverage data (including doctests)
              run: cargo +nightly tarpaulin --verbose --all-features --workspace --timeout 120 --out xml

            - name: Upload to codecov.io
              uses: codecov/codecov-action@5a1091511ad55cbe89839c7260b706298ca349f7 # v5.5.1
              with:
                token: ${{ secrets.CODECOV_TOKEN }}
                verbose: true
                working-directory: .
            - name: Upload coverage reports to Codacy
              uses: codacy/codacy-coverage-reporter-action@89d6c85cfafaec52c72b6c5e8b2878d33104c699 # 1.3.0
              with:
                project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
                coverage-reports: cobertura.xml
                language: Rust
