---
# SPDX-FileCopyrightText: 2023 - 2025 Ali Sajid Imami
#
# SPDX-License-Identifier: Apache-2.0
# SPDX-License-Identifier: MIT
name: Code Coverage
on:
    workflow_call:
jobs:
    test:
        name: Generate Coverage
        runs-on: ubuntu-latest
        container:
            image: xd009642/tarpaulin:develop-nightly@sha256:818d4ea836d6ad6d3814088e4c3c83df0a5dd00fe6daed922b3a27abe3378c5f
            options: --security-opt seccomp=unconfined

        steps:
            - name: Harden Runner
              uses: step-security/harden-runner@6c439dc8bdf85cadbbce9ed30d1c7b959517bc49 # v2.12.2
              with:
                egress-policy: audit
            - name: Checkout repository
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

            - uses: dtolnay/rust-toolchain@b3b07ba8b418998c39fb20f53e8b695cdcc8de1b # nightly
              with:
                toolchain: nightly
                components: llvm-tools-preview

            - name: Install necessary tools
              uses: taiki-e/install-action@726a5c9e4be3a589bab5f60185f0cdde7ed4498e # v2.56.1
              with:
                tool: cargo-llvm-cov,nextest,cargo-tarpaulin

            - name: Collect coverage data (including doctests)
              run: cargo +nightly tarpaulin --verbose --all-features --workspace --timeout 120 --out xml

            - name: Upload to codecov.io
              uses: codecov/codecov-action@18283e04ce6e62d37312384ff67231eb8fd56d24 # v5.4.3
              with:
                token: ${{ secrets.CODECOV_TOKEN }}
                verbose: true
                working-directory: .
            - name: Upload coverage reports to Codacy
              uses: codacy/codacy-coverage-reporter-action@89d6c85cfafaec52c72b6c5e8b2878d33104c699 # 1.3.0
              with:
                project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
                coverage-reports: cobertura.xml
                language: Rust
