---
# SPDX-FileCopyrightText: 2023 - 2025 Ali Sajid Imami
#
# SPDX-License-Identifier: Apache-2.0
# SPDX-License-Identifier: MIT
name: Next semantic-release version
on:
  workflow_call:
    outputs:
      new-release-published:
        description: Indicates whether a new release will be published. The value is a string, either 'true' or 'false'.
        value: ${{ jobs.get-next-version.outputs.new-release-published }}

permissions:
  contents: read

jobs:
  get-next-version:
    name: Get next release version
    runs-on: ubuntu-latest
    outputs:
      new-release-published: ${{ steps.get-next-version.outputs.new-release-published }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            github.com:443
            api.github.com:443
            registry.npmjs.org:443

      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: jdx/mise-action@c2a87611a18de5b3828c5652fe268e992400cb5c # v4.3.0
        with:
          experimental: true

      - name: Get next release version
        id: get-next-version
        env:
          GITHUB_TOKEN: ${{secrets.ACTIONS_PAT_GITHUB}}
        run: |
          : calculate next semantic-release version
          semantic-release \
          --dry-run \
          --plugins semantic-release-export-data \
          --verify-conditions semantic-release-export-data \
          --verify-release '' \
          --generate-notes semantic-release-export-data \
          --prepare '' \
          --publish '' \
          --success '' \
          --fail ''
        shell: bash
